// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzWRpJlBpz1tLesow0zdSRWIfCLSVKbo0',
    appId: '1:260530709859:web:ffdb549ea33c555fcbdf56',
    messagingSenderId: '260530709859',
    projectId: 'mynotes-4989',
    authDomain: 'mynotes-4989.firebaseapp.com',
    storageBucket: 'mynotes-4989.appspot.com',
    measurementId: 'G-8JL0VLT7QB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA58L-lDzeJsTPV71snza79BuzWFD4-nQ',
    appId: '1:260530709859:android:376c63f605645715cbdf56',
    messagingSenderId: '260530709859',
    projectId: 'mynotes-4989',
    storageBucket: 'mynotes-4989.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrKjwKHjseu3g2y04Gjoa7_-HsUOv2Jwc',
    appId: '1:260530709859:ios:c4b077d3d0bc77abcbdf56',
    messagingSenderId: '260530709859',
    projectId: 'mynotes-4989',
    storageBucket: 'mynotes-4989.appspot.com',
    iosClientId: '260530709859-hvfsep6bktmct5njg224irv37g4k5b6g.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrKjwKHjseu3g2y04Gjoa7_-HsUOv2Jwc',
    appId: '1:260530709859:ios:c4b077d3d0bc77abcbdf56',
    messagingSenderId: '260530709859',
    projectId: 'mynotes-4989',
    storageBucket: 'mynotes-4989.appspot.com',
    iosClientId: '260530709859-hvfsep6bktmct5njg224irv37g4k5b6g.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotes',
  );
}
